### ISSUE TITLE
Reporting to be per line

### ISSUE THREAD

**Issue by PaymonK** [Geeksltd/Olive.Microservice.Explorer#11]
Currently at the bottom of the form we are showing a status report message. That should be removed.

Instead, add an icon at the right side of each row for the History of log messages related to that service. When it's clicked, open a new window with a list box showing the last 50 action log messages related to that item. Any operation that fails will also show its error message in there. It would read something like:

```
- 05:09:11  Updated nuget package Olive.Mvc on Domain from 3.2.1 to 3.2.2
- 05:09:10  Failed to update nuget package Olive on Website from 2.2.5 to 2.2.6. Error: ....
- 05:09:08  Service started
- 05:09:02  Service stopped
...
```

**Comment by PaymonK** [comment]
I noticed that we already have the overall Logs file. So simply that features should be launched per row (service) instead of global.

Also remove "Checking only" messages such as "### > Begin ..." or "===> End Nuget ..."

We just need log for actions and results.

**Comment by pharzath** [comment]
Done.
